export default {
    FETCH_POSTS: 'FETCH_POSTS',
    FETCH_POSTS_SUCCEEDED: 'FETCH_POSTS_SUCCEEDED',
    FETCH_POSTS_FAILED: 'FETCH_POSTS_FAILED',
    FETCH_PAGES: 'FETCH_PAGES',
    FETCH_PAGES_SUCCEEDED: 'FETCH_PAGES_SUCCEEDED',
    FETCH_PAGES_FAILED: 'FETCH_PAGES_FAILED',
};